.PHONY: all clean

SHELL=/usr/bin/env bash -eo pipefail

.SECONDARY:

all:
	convert -flatten -density 400 greedy_assembly.pdf -alpha off greedy_assembly.png
	convert -flatten subtraction.pdf -alpha off subtraction.png

clean: ## Clean


